
trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.3.0'
    checkLatest: true
- task: UseDotNet@2
  displayName: 'Use .NET Core 2.1 SDK'
  inputs:
    packageType: sdk
    version: 2.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 SDK'
  inputs:
    packageType: sdk
    version: 3.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: Build Fody
  inputs:
    command: 'build'
    projects: 'NetFabric.Hyperlinq.Build.Fody/NetFabric.Hyperlinq.Build.Fody.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build UnitTests
  inputs:
    command: 'build'
    projects: 'NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build Benchmarks
  inputs:
    command: 'build'
    projects: 'NetFabric.Hyperlinq.Benchmarks/NetFabric.Hyperlinq.Benchmarks.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test and Coverage
  inputs:
    command: 'test'
    projects: 'NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj'    
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:Exclude="[xunit.*]*%2c[System.Interactive]*%2c[NetFabric.Hyperlinq.TestData]*%2c[NetFabric.Hyperlinq.Build]*" /p:ExcludeByAttribute="Obsolete%2cGeneratedCodeAttribute%2cCompilerGeneratedAttribute" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    workingDirectory: 'NetFabric.Hyperlinq.UnitTests'
- task: DotNetCoreCLI@2
  displayName: Report Generator
  inputs:
    command: 'custom'
    projects: 'NetFabric.Hyperlinq.UnitTests/NetFabric.Hyperlinq.UnitTests.csproj'
    custom: 'reportgenerator'
    arguments: '-reports:$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/TestResults/Coverage/Reports'
    workingDirectory: 'NetFabric.Hyperlinq.UnitTests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura' 
    summaryFileLocation: $(Build.SourcesDirectory)/TestResults/Coverage/**/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/TestResults/Coverage/Reports
