//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFabric.Hyperlinq.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetFabric.Hyperlinq.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection has a value type enumerator. Assigning it to an interface cause it to be boxed and method calls to be virtual, affecting peformance..
        /// </summary>
        internal static string AssignmentBoxing_Description {
            get {
                return ResourceManager.GetString("AssignmentBoxing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has a value type enumerator. Assigning it to &apos;{1}&apos; causes boxing of the enumerator..
        /// </summary>
        internal static string AssignmentBoxing_MessageFormat {
            get {
                return ResourceManager.GetString("AssignmentBoxing_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigment to interface causes boxing of enumerator.
        /// </summary>
        internal static string AssignmentBoxing_Title {
            get {
                return ResourceManager.GetString("AssignmentBoxing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public methods should return highest admissible level interface..
        /// </summary>
        internal static string HighestLevelInterface_Description {
            get {
                return ResourceManager.GetString("HighestLevelInterface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider returning &apos;{0}&apos; instead..
        /// </summary>
        internal static string HighestLevelInterface_MessageFormat {
            get {
                return ResourceManager.GetString("HighestLevelInterface_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public methods should return highest admissible level interface..
        /// </summary>
        internal static string HighestLevelInterface_Title {
            get {
                return ResourceManager.GetString("HighestLevelInterface_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerable can be empty but not null. &apos;foreach&apos; does not check for null..
        /// </summary>
        internal static string NullEnumerable_Description {
            get {
                return ResourceManager.GetString("NullEnumerable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerable cannot be null..
        /// </summary>
        internal static string NullEnumerable_MessageFormat {
            get {
                return ResourceManager.GetString("NullEnumerable_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerable cannot be null..
        /// </summary>
        internal static string NullEnumerable_Title {
            get {
                return ResourceManager.GetString("NullEnumerable_Title", resourceCulture);
            }
        }
    }
}
